In [17]:
import cma
import numpy as np
from cma.constraints_handler import AugmentedLagrangian, PopulationEvaluator

In [29]:
# es = cma.CMAEvolutionStrategy(3 * [0], 0.5)
# actual_solution = np.array([1.,0.,1.])
# while not es.stop():
#     solutions = es.ask()
#     print(solutions[0])
#     es.tell(solutions, [np.sum(np.abs(solution - actual_solution)) for solution in solutions])

In [30]:
m = 2 #constraints

In [55]:
actual_solution = np.array([1.,0.,1.])
def objective(x):
    return np.sum(np.abs(x - actual_solution))

def constraints(x):
    return np.array([1 - x[1]])

In [56]:
es = cma.CMAEvolutionStrategy(3 * [1], 1, {'termination_callback': lambda es: sum(es.mean**2) < 1e-8})
al = AugmentedLagrangian(es.N)

(3_w,7)-aCMA-ES (mu_w=2.3,w_1=58%) in dimension 3 (seed=398895, Sun Dec  6 18:00:17 2020)


In [57]:
while not es.stop():
    solutions = es.ask()
    print(solutions[0], len(solutions))
    eva = PopulationEvaluator(objective, constraints)(solutions, m=es.mean)
    al.set_coefficients(eva.F, eva.G)  # set lam and mu, not part of the original algorithm
    al.update(eva.m['f'], eva.m['g'])
    es.tell(eva.X, [f + sum(al(g)) for f, g in zip(eva.F, eva.G)])

[0.26852632 0.81104891 2.54320291] 7
[2.38525718 2.09045648 1.2488459 ] 7
[0.83787503 1.53456187 1.3529117 ] 7
[1.0072013  0.24879863 0.99561564] 7
[1.24042046 0.39946471 0.89544438] 7
[ 1.0723616  -0.22300702  0.4640177 ] 7
[0.99371008 0.41947551 1.08593847] 7
[0.68119501 0.58518705 0.78583671] 7
[1.21781547 0.40189856 0.96475542] 7
[1.09867479 0.29229791 0.85321253] 7
[1.01412138 0.13899925 0.85753759] 7
[0.92537688 0.29327863 0.99395182] 7
[0.93886648 0.30777263 0.90888027] 7
[0.97429993 0.39012324 1.03259576] 7
[0.97469505 0.39527089 0.97568635] 7
[0.98545395 0.23992558 0.96555049] 7
[0.94305453 0.22576658 1.02106323] 7
[0.99073636 0.28975965 0.98744719] 7
[1.01877531 0.06451166 0.88626731] 7
[0.92758785 0.03741094 0.93424718] 7
[0.99744977 0.05199022 0.96263055] 7
[1.01918233 0.01432624 0.93638876] 7
[ 0.98958054 -0.08632849  0.97950418] 7
[0.99368079 0.10873541 1.00485976] 7
[1.00144716 0.10804314 1.03297398] 7
[1.00616335 0.10660257 0.98969052] 7
[1.01427781 0.02658443 0.9700852