In [1]:
import cma
import numpy as np
from cma.constraints_handler import AugmentedLagrangian, PopulationEvaluator

In [7]:
es = cma.CMAEvolutionStrategy(3 * [0], 0.5, {'bounds': [0, .75]})
actual_solution = np.array([1.,0.,1.])
while not es.stop():
    solutions = es.ask()
    print(solutions[0])
    es.tell(solutions, [np.sum(np.abs(solution - actual_solution)) for solution in solutions])

(3_w,7)-aCMA-ES (mu_w=2.3,w_1=58%) in dimension 3 (seed=552857, Tue Dec  8 20:34:49 2020)
[0.12145617 0.0135992  0.5795688 ]
[0.46249146 0.69510974 0.16936306]
[0.50170662 0.10815065 0.63778183]
[0.47822211 0.08606523 0.57038421]
[0.61968262 0.47547398 0.56333308]
[0.58548522 0.20204439 0.05994787]
[0.73551957 0.01252447 0.6524252 ]
[0.50900662 0.06499097 0.71714457]
[0.39664683 0.27030792 0.71547125]
[0.46460545 0.01654824 0.55564665]
[0.72646061 0.03185006 0.48718814]
[0.61279511 0.1578972  0.74565096]
[5.35540754e-01 6.25173427e-06 7.48704862e-01]
[0.74805255 0.00679373 0.68471656]
[7.07789621e-01 5.10034510e-04 7.47820527e-01]
[7.26861549e-01 1.34938285e-04 6.95590480e-01]
[0.74320685 0.00974571 0.74617484]
[0.7480349  0.00755542 0.74961464]
[0.73319215 0.01403671 0.74987418]
[0.74895921 0.00539457 0.73056762]
[7.48765612e-01 8.40255244e-05 7.49999356e-01]
[0.74893476 0.00126571 0.743393  ]
[0.74975613 0.00222707 0.74976452]
[0.74988487 0.00208263 0.74927573]
[0.74990353 0.00129743

In [ ]:
m = 2 #constraints

In [ ]:
actual_solution = np.array([1.,0.,1.])
def objective(x):
    return np.sum(np.abs(x - actual_solution))

def constraints(x):
    return np.array([1 - x[1]])

In [ ]:
es = cma.CMAEvolutionStrategy(3 * [1], 1, {'termination_callback': lambda es: sum(es.mean**2) < 1e-8})
al = AugmentedLagrangian(es.N)

In [ ]:
while not es.stop():
    solutions = es.ask()
    print(solutions[0], len(solutions))
    eva = PopulationEvaluator(objective, constraints)(solutions, m=es.mean)
    al.set_coefficients(eva.F, eva.G)  # set lam and mu, not part of the original algorithm
    al.update(eva.m['f'], eva.m['g'])
    es.tell(eva.X, [f + sum(al(g)) for f, g in zip(eva.F, eva.G)])

***try constraints***

In [3]:
es = cma.fmin(cma.ff.elli, 6 * [1], 1,
                   {'BoundaryHandler': cma.BoundPenalty,
                    'bounds': [-.75, .75],
                    })  # doctest: +ELLIPSIS

(4_w,9)-aCMA-ES (mu_w=2.8,w_1=49%) in dimension 6 (seed=528980, Tue Dec  8 20:29:16 2020)
Iterat #Fevals   function value  axis ratio  sigma  min&max std  t[m:s]
    1      9 6.204599772449403e+04 1.0e+00 9.18e-01  9e-01  9e-01 0:00.0
    2     18 1.199215028565669e+04 1.2e+00 8.46e-01  8e-01  9e-01 0:00.0
    3     27 1.788220618914653e+03 1.4e+00 7.86e-01  7e-01  8e-01 0:00.0
  100    900 1.290334707956516e-01 1.9e+02 2.26e-02  3e-04  3e-02 0:00.2
  200   1800 4.442728154275251e-09 9.1e+02 5.03e-05  4e-08  4e-05 0:00.4
  256   2304 4.705125381499655e-15 9.1e+02 1.96e-07  4e-11  4e-08 0:00.4
termination on tolfun=1e-11 (Tue Dec  8 20:29:17 2020)
final/bestever f-value = 1.788203e-15 1.788203e-15
incumbent solution: [-3.26944410133302e-08, 2.9357886600925202e-09, 4.963295956465563e-10, 4.614811575044058e-11, -3.567907701664081e-11, -2.078459932124521e-11]
std deviation: [3.5895397614577026e-08, 9.58595925510066e-09, 2.6418341468894914e-09, 7.59554646370834e-10, 1.8267146539745963e-10, 

In [5]:
es

(array([-3.26944410e-08,  2.93578866e-09,  4.96329596e-10,  4.61481158e-11,
        -3.56790770e-11, -2.07845993e-11]),
 1.7882032052299754e-15,
 2305,
 2305,
 256,
 array([-3.26944410e-08,  2.93578866e-09,  4.96329596e-10,  4.61481158e-11,
        -3.56790770e-11, -2.07845993e-11]),
 array([3.58953976e-08, 9.58595926e-09, 2.64183415e-09, 7.59554646e-10,
        1.82671465e-10, 3.80697877e-11]),
 {'tolfun': 1e-11},
 {'tolfun': 1e-11},
 <cma.logger.CMADataLogger at 0x1d5e7214588>)

AttributeError: 'tuple' object has no attribute 'stop'