In [1]:
import numpy as np
from scipy import stats
from lib.DataManager import *
from lib.PolicyStats import *

In [2]:
num_states = 18
num_actions = 4
gamma = 0.95

In [3]:
histories = GetHistories("data\data.csv", gamma)

line 0
line 1000000
line 2000000
line 3000000
line 4000000
line 5000000
line 6000000
line 7000000
line 8000000
line 9000000
line 10000000
line 11000000
line 12000000
line 13000000
line 14000000
line 15000000
line 16000000
line 17000000
line 18000000
line 19000000
line 20000000
line 21000000
line 22000000
line 23000000
line 24000000
line 25000000
line 26000000
line 27000000
line 28000000
line 29000000
line 30000000
line 31000000
line 32000000
line 33000000
line 34000000
line 35000000
line 36000000
line 37000000
line 38000000
line 39000000
line 40000000
line 41000000
line 42000000
line 43000000
line 44000000
line 45000000
line 46000000
line 47000000
line 48000000
line 49000000
line 50000000
line 51000000
line 52000000
line 53000000
line 54000000
line 55000000
line 56000000
line 57000000
line 58000000
line 59000000
line 60000000
line 61000000
line 62000000


In [4]:
avg_returns = np.zeros((num_states,num_actions))
visit_count = np.zeros((num_states,num_actions))
for traj in histories:
    total_return = traj["return"]
    states = traj["St"]
    actions = traj["At"]
    avg_returns[states, actions] += total_return
    visit_count[states, actions] += 1
    
avg_returns /= visit_count
print(avg_returns)
    
    

C:\Users\mfcli\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: RuntimeWarning: invalid value encountered in true_divide
  # Remove the CWD from sys.path while we load stuff.


[[0.90173656 1.01448076 0.90366319 1.01260974]
 [0.75448454 0.85712337 0.7379564  0.8590507 ]
 [0.66805473 0.77856771 0.64050155 0.73393074]
 [0.61952511 0.74602444 0.60656186 0.62031144]
 [0.73698428 0.85936001 0.76036595 0.85967599]
 [0.68429104 0.84149655 0.68306061 0.84041333]
 [0.63822393 0.86200497 0.63668589 0.79241709]
 [0.61041572 0.92250729 0.64157463 0.68931493]
 [0.64069305 0.73516115 0.66984501 0.77909927]
 [0.64047618 0.79171919 0.64054935 0.86143708]
 [0.64400119 0.92335176 0.64277354 0.92781911]
 [0.64531241 1.17327574 0.70143849 0.83152127]
 [0.60736169 0.62182635 0.62057355 0.7481903 ]
 [0.64437295 0.68702019 0.61071078 0.92155374]
 [0.69917495 0.82731494 0.64301256 1.17192212]
 [       nan        nan        nan        nan]
 [1.54810183 1.54756594 0.79357213 0.80284125]
 [0.92112874 0.92122655 1.92610781 1.92799767]]


In [9]:
visit_count = np.zeros((num_states,num_states,num_actions))
for traj in histories:
    cur_states = traj["St"][:-1]
    next_states = traj["St"][1:]
    actions = traj["At"][:-1]
    visit_count[cur_states, next_states, actions] += 1
    
print(visit_count)
    

[[[649146.      0. 649945.      0.]
  [     0.      0.      0. 787569.]
  [     0.      0.      0.      0.]
  ...
  [     0.      0.      0.      0.]
  [     0.      0.      0.      0.]
  [     0.      0.      0.      0.]]

 [[     0.      0. 575844.      0.]
  [530482.      0.      0.      0.]
  [     0.      0.      0. 623698.]
  ...
  [     0.      0.      0.      0.]
  [     0.      0.      0.      0.]
  [     0.      0.      0.      0.]]

 [[     0.      0.      0.      0.]
  [     0.      0. 492656.      0.]
  [435275.      0.      0.      0.]
  ...
  [     0.      0.      0.      0.]
  [     0.      0.      0.      0.]
  [     0.      0.      0.      0.]]

 ...

 [[     0.      0.      0.      0.]
  [     0.      0.      0.      0.]
  [     0.      0.      0.      0.]
  ...
  [     0.      0.      0.      0.]
  [     0.      0.      0.      0.]
  [     0.      0.      0.      0.]]

 [[249261. 250186. 250844. 249709.]
  [     0.      0.      0.      0.]
  [     0.      0.      0.

In [36]:
result = ""
for i in range(visit_count.shape[0]):
    print("---state " + str(i) + "---")
    state_transitions = visit_count[i]
    possible_transitions = np.where(np.sum(state_transitions,axis=1) > 0)[0]
    for ns in possible_transitions:
        actions = list(np.where(state_transitions[ns] != 0)[0])
        result += str(i) + " " + str(ns) + " " + ",".join(str(a) for a in actions) + "\n"  
        print(ns, state_transitions[ns])
    print("------------------")
print(result)

---state 0---
0 [649146.      0. 649945.      0.]
1 [     0.      0.      0. 787569.]
4 [     0. 787661.      0.      0.]
------------------
---state 1---
0 [     0.      0. 575844.      0.]
1 [530482.      0.      0.      0.]
2 [     0.      0.      0. 623698.]
5 [     0. 632913.      0.      0.]
------------------
---state 2---
1 [     0.      0. 492656.      0.]
2 [435275.      0.      0.      0.]
3 [     0.      0.      0. 490060.]
6 [     0. 530604.      0.      0.]
------------------
---state 3---
2 [     0.      0. 424633.      0.]
3 [354657.      0.      0. 355038.]
7 [     0. 454197.      0.      0.]
------------------
---state 4---
0 [574773.      0.      0.      0.]
4 [     0.      0. 530461.      0.]
5 [     0.      0.      0. 633198.]
8 [     0. 623897.      0.      0.]
------------------
---state 5---
1 [533009.      0.      0.      0.]
4 [     0.      0. 532638.      0.]
6 [     0.      0.      0. 587716.]
9 [     0. 587253.      0.      0.]
------------------
---state 6

array([[     0.,      0., 575844.,      0.],
       [530482.,      0.,      0.,      0.],
       [     0.,      0.,      0., 623698.],
       [     0.,      0.,      0.,      0.],
       [     0.,      0.,      0.,      0.],
       [     0., 632913.,      0.,      0.],
       [     0.,      0.,      0.,      0.],
       [     0.,      0.,      0.,      0.],
       [     0.,      0.,      0.,      0.],
       [     0.,      0.,      0.,      0.],
       [     0.,      0.,      0.,      0.],
       [     0.,      0.,      0.,      0.],
       [     0.,      0.,      0.,      0.],
       [     0.,      0.,      0.,      0.],
       [     0.,      0.,      0.,      0.],
       [     0.,      0.,      0.,      0.],
       [     0.,      0.,      0.,      0.],
       [     0.,      0.,      0.,      0.]])