In [20]:
import numpy as np
from lib.DataManager import *
from lib.PolicyStats import *

In [28]:
policies_dir = "C:\\Users\\mfcli\\Documents\\School\\F20\\687\\rl-policy-improvement\\" #PATH TO POLCICIES DIR

In [29]:
num_states = 18
num_actions = 4

In [31]:
i = 1
path = "policy" + str(i) + ".txt"
solution = LoadSolutionFromTxt(policies_dir + path, num_states, num_actions)

In [32]:
def policy_softmax(policy):
    numerators = np.exp(policy)
    return (numerators.T / np.sum(numerators, axis=1)).T

In [37]:
new_policy = policy_softmax(solution)
print(new_policy)

[[1.48786575e-02 7.88295997e-01 4.36278209e-04 1.96389068e-01]
 [3.22379521e-04 9.19488126e-01 2.13318917e-02 5.88576032e-02]
 [4.04828892e-01 5.49193632e-01 4.59570942e-02 2.03821238e-05]
 [6.33727801e-02 6.66067819e-04 7.62108871e-01 1.73852281e-01]
 [6.93656455e-05 7.76935829e-02 5.16974868e-01 4.05262184e-01]
 [3.16648607e-05 1.29303068e-04 2.94997050e-08 9.99839003e-01]
 [8.70683305e-02 3.44651572e-01 6.37842684e-03 5.61901671e-01]
 [1.61804178e-04 9.07455483e-01 8.18284660e-02 1.05542464e-02]
 [7.74258790e-01 7.94166234e-04 1.20203142e-04 2.24826840e-01]
 [3.10774655e-03 4.05215825e-04 3.72374220e-07 9.96486665e-01]
 [4.64520438e-04 2.04731288e-04 2.22410102e-02 9.77089738e-01]
 [2.13348585e-03 9.95807807e-01 5.91678969e-05 1.99953944e-03]
 [9.88711434e-01 3.97825689e-03 6.99170645e-03 3.18602492e-04]
 [9.90705000e-01 5.88974888e-03 2.23424015e-04 3.18182709e-03]
 [9.98528806e-01 6.78120622e-05 7.95122037e-05 1.32387003e-03]
 [1.43998196e-02 9.84805255e-01 7.79108170e-04 1.581712

In [34]:
greed_policy = np.argmax(new_policy,axis=1)

print(greed_policy[-2:])
print(greed_policy[:-2].reshape(4,4))

[1 1]
[[1 1 1 2]
 [2 3 3 1]
 [0 3 3 1]
 [0 0 0 1]]
