In [1]:
import numpy as np
from scipy import stats
from lib.DataManager import *
from lib.PolicyStats import *
from lib.Gridworld import *
from lib.Mockworld import *
import os
import cma
from cma.constraints_handler import AugmentedLagrangian, PopulationEvaluator
from IPython import display
import pickle

In [2]:
policies_dir = "C:\\Users\\mfcli\\Documents\\School\\F20\\687\\rl-policy-improvement\\" #PATH TO POLCICIES DIR

In [3]:
%load_ext autoreload
%autoreload 2

In [4]:
num_states = 18
num_actions = 4
gamma = 0.95
delta = 0.01
USE_PDIS = False
es_path = "pickles/van/saved-cma-PDIS-20.pkl"

In [5]:
es = pickle.load(open(es_path, "rb"))
print("ES_Convergence : " + str(sum(es.mean**2)))

ES_Convergence : 96.95363637086997


In [13]:
i = 52
path = "policy" + str(i) + ".txt"
solution = LoadSolutionFromTxt(policies_dir + path, num_states, num_actions)
print(solution)

[[ 0.03161006  0.26780965 -1.01359704 -1.67823321]
 [-0.46051264  1.16879679 -1.25463329  0.03385143]
 [ 0.7153404   1.80633033 -1.70216774 -0.59761643]
 [-1.08521577 -0.58794894 -0.01763329  0.20279228]
 [-0.14401615  1.58797615 -0.99136062  1.9674264 ]
 [-1.80937065  2.04742834  0.10963905 -0.61151102]
 [-1.01968628  0.99023816  1.53403692  1.65883713]
 [-1.33611728  1.15993218  0.99389051 -0.41680604]
 [-0.88602544  2.21349355 -0.40083784  0.24044395]
 [-1.93705856  1.94014309 -1.72710407 -0.91755077]
 [-0.66831714  0.76924395  0.33136741 -0.73140868]
 [-0.26174331  1.2207939  -0.29418432  0.99439654]
 [-0.38619713 -2.10818568 -3.30394636  2.74169809]
 [-0.58350615 -0.65438159 -0.43227923  3.06925962]
 [-2.5546891  -0.71164196 -2.13477375  1.90739844]
 [ 1.          1.          1.          1.        ]
 [-2.43044915 -2.80385997  0.18113117  3.30194342]
 [-0.88950078 -0.87644056  0.3927787   2.36843342]]


In [14]:
other_solution = es.ask(1)[0].reshape(num_states, num_actions)
print(other_solution)

[[-1.63036554 -2.13712356 -0.75465464  1.85559699]
 [-1.51615156 -0.59172473 -1.48644822  0.22377632]
 [-0.28920805  0.99476327 -1.57995042 -1.10176389]
 [ 0.79926837  0.73278041  0.87856547  0.81572841]
 [-0.4866192   1.80871845  0.50644994  1.05536161]
 [-0.07261063  1.2298686  -0.0930012  -0.52438678]
 [-0.35996997  1.77597238 -1.11882192 -1.04284472]
 [-0.6108638   1.81126792 -0.59717598  0.27023102]
 [-1.31713311  1.05059525 -0.47137032 -0.65932378]
 [-0.29082585  0.36875546  0.5600496   0.76769148]
 [-1.96173917 -0.92154578 -1.77954179  0.99698912]
 [-0.37770078  1.21192533 -1.97556045 -0.54228363]
 [ 1.49666625  0.23122322 -0.50820528  0.15695249]
 [ 0.93314148  0.73286227 -0.82693839  2.57860063]
 [-0.27119482 -1.37272966  0.03668457  2.26635295]
 [-0.45912823  1.21300868  0.34838734 -0.46330919]
 [-0.98185847 -0.86927898  1.56295027  2.73659999]
 [-1.01688701 -2.1933585  -0.02373731  2.75597309]]


[[-2.43044915 -2.80385997  0.18113117  3.30194342]
 [-0.88950078 -0.87644056  0.3927787   2.36843342]]


In [16]:
max_dist = 0
farthest_solution = None
for j in range(50, 100):
    path = "policy" + str(j + 1) + ".txt"
    temp_solution = LoadSolutionFromTxt(policies_dir + path, num_states, num_actions)
    solution = solution[:1,:]
    temp_solution = temp_solution[:1,:]
    dist = np.linalg.norm(solution - temp_solution)
    if (dist > max_dist):
        print(j+1)
        max_dist = dist
        farthest_solution = temp_solution
print(max_dist)
print(farthest_solution)
print("vs")
print(solution)
other_solution = farthest_solution

51
53
54
57
59
66
96
3.159133952018084
[[0.08821855 0.84698666 0.30637036 1.13231173]]
vs
[[ 0.03161006  0.26780965 -1.01359704 -1.67823321]]


In [74]:
def policy_softmax(policy):
    numerators = np.exp(policy)
    return (numerators.T / np.sum(numerators, axis=1)).T

In [82]:
new_policy = policy_softmax(solution)
other_policy = policy_softmax(other_solution)
print(np.argmax(new_policy, axis=1))
print(np.argmax(other_policy, axis=1))
print(np.linalg.norm(new_policy - other_policy))

[1 1 1 3 3 1 3 1 1 1 1 1 3 3 3 0 3 3]
[3 3 1 3 1 2 1 1 1 1 3 1 0 3 3 1 3 3]
2.22977055110787


In [41]:
path = "data\data.csv"
histories = GetHistories(path, gamma)

line 0
line 1000000
line 2000000
line 3000000
line 4000000
line 5000000
line 6000000
line 7000000
line 8000000
line 9000000
line 10000000
line 11000000
line 12000000
line 13000000
line 14000000
line 15000000
line 16000000
line 17000000
line 18000000
line 19000000
line 20000000
line 21000000
line 22000000
line 23000000
line 24000000
line 25000000
line 26000000
line 27000000
line 28000000
line 29000000
line 30000000
line 31000000
line 32000000
line 33000000
line 34000000
line 35000000
line 36000000
line 37000000
line 38000000
line 39000000
line 40000000
line 41000000
line 42000000
line 43000000
line 44000000
line 45000000
line 46000000
line 47000000
line 48000000
line 49000000
line 50000000
line 51000000
line 52000000
line 53000000
line 54000000
line 55000000
line 56000000
line 57000000
line 58000000
line 59000000
line 60000000
line 61000000
line 62000000


In [43]:
train, test = SplitData(histories)

800000
200000


In [44]:
exploration_policy = GetPolicy(train, num_states, num_actions, 1000)
print(exploration_policy)

[[0.25  0.25  0.25  0.25 ]
 [0.25  0.25  0.25  0.25 ]
 [0.25  0.25  0.25  0.25 ]
 [0.25  0.25  0.25  0.25 ]
 [0.25  0.25  0.25  0.25 ]
 [0.25  0.25  0.25  0.25 ]
 [0.25  0.25  0.25  0.25 ]
 [0.25  0.25  0.25  0.25 ]
 [0.25  0.25  0.25  0.25 ]
 [0.25  0.25  0.25  0.25 ]
 [0.25  0.25  0.25  0.25 ]
 [0.25  0.25  0.25  0.25 ]
 [0.25  0.25  0.25  0.25 ]
 [0.25  0.25  0.25  0.25 ]
 [0.25  0.25  0.25  0.25 ]
 [0.    0.    0.    0.   ]
 [0.25  0.25  0.25  0.25 ]
 [0.375 0.375 0.125 0.125]]


In [71]:
ISFunc = ImportanceSampling
if(USE_PDIS):
    ISFunc = PDImportanceSampling

In [72]:
print(Safety_Prediction(train, exploration_policy, gamma, new_policy, ISFunc, delta, len(test), None))

7.710688164186677 508.4916303919843 2.326366519648287 447.21359549995793
2.420429029095625


In [76]:
import math
import numpy as np
import sys
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from scipy.stats import t
from scipy.optimize import minimize # The black-box optimization algorithm used to find a candidate solution

np.set_printoptions(precision=5, suppress=True)


# This function returns the inverse of Student's t CDF using the degrees of freedom in nu for the corresponding
# probabilities in p. It is a Python implementation of Matlab's tinv function: https://www.mathworks.com/help/stats/tinv.html
def tinv(p, nu):
	return t.ppf(p, nu)


# This function computes the sample standard deviation of the vector v, with Bessel's correction
def stddev(v):
	n = v.size
	variance = (np.var(v) * n) / (n-1) # Variance with Bessel's correction
	return np.sqrt(variance)           # Compute the standard deviation


# This function computes a (1-delta)-confidence upper bound on the expected value of a random
# variable using Student's t-test. It analyzes the data in v, which holds i.i.d. samples of the random variable.
# The upper confidence bound is given by 
#    sampleMean + sampleStandardDeviation/sqrt(n) * tinv(1-delta, n-1),
#    where n is the number of points in v.
def ttestUpperBound(v, delta):	
	n  = v.size
	res = v.mean() + stddev(v) / math.sqrt(n) * tinv(1.0 - delta, n - 1)
	return res


# This function works similarly to ttestUpperBound, but returns a conservative upper bound. It uses 
# data in the vector v (i.i.d. samples of a random variable) to compute the relevant statistics 
# (mean and standard deviation) but assumes that the number of points being analyzed is k instead of |v|.
# This function is used to estimate what the output of ttestUpperBound would be if it were to
# be run on a new vector, v, containing values sampled from the same distribution as
# the points in v. The 2.0 factor in the calculation is used to double the width of the confidence interval,
# when predicting the outcome of the safety test, in order to make the algorithm less confident/more conservative.
def predictTTestUpperBound(v, delta, k):
	# conservative prediction of what the upper bound will be in the safety test for the a given constraint
	print(v.mean(), stddev(v), tinv(1.0 - delta, k - 1), math.sqrt(k))
	res = v.mean() - 2.0 * stddev(v) / math.sqrt(k) * tinv(1.0 - delta, k - 1)
	return res
	


In [67]:
v = []
for ep in range(len(train)):
    # if(ep % update_freq == 0):
    #     print(str(ep) + " / " + str(len(histories)))
    v.append(ISFunc(train[ep], exploration_policy, gamma, new_policy))
v = np.array(v)

In [77]:
print(predictTTestUpperBound(v, delta, len(test)))

7.710688164187135 508.49163039202347 2.326366519648287 447.21359549995793
2.4204290290956765
